server:
  port: 80
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tavern?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123
  redis:
    host: localhost
    port: 6379