version: '3'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: tavern
    restart: always
    volumes:
      - ./backend/src/main/resources/sql/tavern.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tavern-network
  
  backend:
    image: tavern-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mysqldb
    restart: always
    networks:
      - tavern-network
  
  frontend:
    image: tavern-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    networks:
      - tavern-network
  
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    ports:
      - 8080:8080
    restart: always
    networks:
      - tavern-network

networks:
  tavern-network: